input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 2; index++) {
        music.playTone(523, music.beat(BeatFraction.Double))
        music.playTone(784, music.beat(BeatFraction.Double))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(1042, music.beat(BeatFraction.Double))
        music.playTone(784, music.beat(BeatFraction.Whole))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(1042, music.beat(BeatFraction.Double))
        music.playTone(784, music.beat(BeatFraction.Whole))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Double))
        music.rest(music.beat(BeatFraction.Whole))
        music.playTone(784, music.beat(BeatFraction.Whole))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Half))
    }
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(1044, music.beat(BeatFraction.Half))
    music.playTone(988, music.beat(BeatFraction.Half))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(740, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(1044, music.beat(BeatFraction.Half))
    music.playTone(988, music.beat(BeatFraction.Half))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.playTone(1174, music.beat(BeatFraction.Whole))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Double))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(1044, music.beat(BeatFraction.Half))
    music.playTone(988, music.beat(BeatFraction.Half))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(740, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1570, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(1397, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1308, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1044, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(988, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.playTone(1174, music.beat(BeatFraction.Double))
    music.playTone(1174, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    for (let index = 0; index < 2; index++) {
        music.playTone(523, music.beat(BeatFraction.Double))
        music.playTone(784, music.beat(BeatFraction.Double))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(1042, music.beat(BeatFraction.Double))
        music.playTone(784, music.beat(BeatFraction.Whole))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(1042, music.beat(BeatFraction.Double))
        music.playTone(784, music.beat(BeatFraction.Whole))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Double))
        music.rest(music.beat(BeatFraction.Whole))
        music.playTone(784, music.beat(BeatFraction.Whole))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Half))
    }
})
input.onButtonPressed(Button.B, function () {
    if (light2 == 0) {
        strip = neopixel.create(DigitalPin.P2, 14, NeoPixelMode.RGB)
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        light2 = 1
        pins.digitalWritePin(DigitalPin.P0, 1)
        pins.digitalWritePin(DigitalPin.P1, 1)
    } else {
        pins.digitalWritePin(DigitalPin.P0, 0)
        strip.clear()
    }
})
let strip: neopixel.Strip = null
let light2 = 0
light2 = 0
